// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: coordination/coordination.proto

package coordination

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordinationClient is the client API for Coordination service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationClient interface {
	// one message is sent and one is recieved
	Increment(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error)
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// many messages are sent and one is recieved
	SayHi(ctx context.Context, opts ...grpc.CallOption) (Coordination_SayHiClient, error)
}

type coordinationClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationClient(cc grpc.ClientConnInterface) CoordinationClient {
	return &coordinationClient{cc}
}

func (c *coordinationClient) Increment(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/coordination.Coordination/Increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/coordination.Coordination/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationClient) SayHi(ctx context.Context, opts ...grpc.CallOption) (Coordination_SayHiClient, error) {
	stream, err := c.cc.NewStream(ctx, &Coordination_ServiceDesc.Streams[0], "/coordination.Coordination/SayHi", opts...)
	if err != nil {
		return nil, err
	}
	x := &coordinationSayHiClient{stream}
	return x, nil
}

type Coordination_SayHiClient interface {
	Send(*Greeding) error
	CloseAndRecv() (*Farewell, error)
	grpc.ClientStream
}

type coordinationSayHiClient struct {
	grpc.ClientStream
}

func (x *coordinationSayHiClient) Send(m *Greeding) error {
	return x.ClientStream.SendMsg(m)
}

func (x *coordinationSayHiClient) CloseAndRecv() (*Farewell, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Farewell)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoordinationServer is the server API for Coordination service.
// All implementations must embed UnimplementedCoordinationServer
// for forward compatibility
type CoordinationServer interface {
	// one message is sent and one is recieved
	Increment(context.Context, *Amount) (*Ack, error)
	Ping(context.Context, *Request) (*Reply, error)
	// many messages are sent and one is recieved
	SayHi(Coordination_SayHiServer) error
	mustEmbedUnimplementedCoordinationServer()
}

// UnimplementedCoordinationServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinationServer struct {
}

func (UnimplementedCoordinationServer) Increment(context.Context, *Amount) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedCoordinationServer) Ping(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCoordinationServer) SayHi(Coordination_SayHiServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedCoordinationServer) mustEmbedUnimplementedCoordinationServer() {}

// UnsafeCoordinationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServer will
// result in compilation errors.
type UnsafeCoordinationServer interface {
	mustEmbedUnimplementedCoordinationServer()
}

func RegisterCoordinationServer(s grpc.ServiceRegistrar, srv CoordinationServer) {
	s.RegisterService(&Coordination_ServiceDesc, srv)
}

func _Coordination_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordination.Coordination/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServer).Increment(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordination_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordination.Coordination/ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordination_SayHi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinationServer).SayHi(&coordinationSayHiServer{stream})
}

type Coordination_SayHiServer interface {
	SendAndClose(*Farewell) error
	Recv() (*Greeding, error)
	grpc.ServerStream
}

type coordinationSayHiServer struct {
	grpc.ServerStream
}

func (x *coordinationSayHiServer) SendAndClose(m *Farewell) error {
	return x.ServerStream.SendMsg(m)
}

func (x *coordinationSayHiServer) Recv() (*Greeding, error) {
	m := new(Greeding)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Coordination_ServiceDesc is the grpc.ServiceDesc for Coordination service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordination_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordination.Coordination",
	HandlerType: (*CoordinationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Increment",
			Handler:    _Coordination_Increment_Handler,
		},
		{
			MethodName: "ping",
			Handler:    _Coordination_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHi",
			Handler:       _Coordination_SayHi_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "coordination/coordination.proto",
}
